CONFIG_ZMK_POINTING=y
CONFIG_ZMK_SLEEP=y
# disabled due to a bug in power management
# [fix(pm): add state check to soft off device suspension by carrefinho · Pull Request #3102 · zmkfirmware/zmk](https://github.com/zmkfirmware/zmk/pull/3102)
# CONFIG_ZMK_PM_SOFT_OFF=y
